
global.banishedTimes = 0
create_textevent(["I don't feel so good...",
				"Like...something is missing...",
				"What's over there?!",
				"Stell'bsna ya! orr'e hupadgh n'ghft!hrii li'hee grah'n!",
				"That's it! The Monster!",
				"There's color around it...It stole our color!",
				"We should...Defeat it...No matter sacrificing what...",
				"Hastur: Wait a minute, my believer.",
				"First time to see, I'm Hastur.",
				"To say more accurately, they call me Hastur.",
				"I know you are doubting me, yes, I took away your color and life.",
				"I have disturbed your lives, your world, your all things.",
				"To be precise, I have no guilt.",
				"*fizz* Use the Banished Rune by now! Quick! Don't listen to him!",
				["Use Banished Rune"],
				"(Banished Rune is used)",
				"Hastur:You are a true believer of mine.",
				"You may have forgotten what was written in the Necronomicon, the misuse of runes will only hasten my arrival.",
				"Do you think this will work? Look, I know you hate me.",
				"Didn't you have sacrificing runes?",
				"Well, if you use this to sacrifice one of your teammates, then I'll tell you how to defeat me.",
				"A good deal, uh?",
				["Do Not Use"],
				
				"(Runes aren't used)",
				"Please sacrifice me...I can use my life to make my teammates back to ordinary people.",
				"It doesn't matter whether I'm alive or not.",
				"Please...",
				"If you use Banished again, you would have less time.",
				"I don't know what would happen if we have less time...",
				"But I remember that Banished should be used for many times, should we use it again?",
				["Use Banished Rune"],
				
				"(Banish is used)",
				"Hastur:Not enough yet...You can never defeat me with those stupid rune.",
				"Never...",
				"You know, the world is only in a thing you called computer.",
				"They are all meaningless and boring data.",
				"But you, are different.",
				"I see the lights in your eyes.",
				"And your memory...much precious memory, in your computer.",
				"I need it, I want it, and I want to know more about it.",
				"Sacrifice it to me, and I'll tell you all about this world.",
				"Think preciously and quickly, you don't have too much time to hesitate",
				["Sacrifice You MEMORY","Use Banished Rune"],
				"...",
				"..."],"None",
				-1,
				-1,
				[0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1],
				[0,0,0,0,0,0,0,0,0,0,0,0,0,0,[15],0,0,0,0,0,0,0,[23],0,0,0,0,0,0,0,[31],0,0,0,0,0,0,0,0,0,0,0,[43,44]],
				[0,0,0,0,0,0,0,0,0,0,0,0,0,[s_removeItem,"Banished"],0,0,0,0,0,0,0,[s_removeItem,"Sacrifices"],0,0,0,0,0,0,0,[s_removeItem,"Banished"],0,0,0,0,0,0,0,0,0,0,0,0,0,[s_JumpToEnd2],[s_removeItem,"Banished"]]);
				
global.reverse = true;